config/routes.rb
ClientSampler::Application.routes.draw do

  root 'main#index'
  get 'about' => 'main#about'

  resources :clients, only: [:index] do
    collection do
      get 'privacy' => 'clients#privacy'
      get 'collect' => 'collector#index'
      get 'collect/:protocol' => 'collector#collect'
    end
  end

  resources :servers, only: [:index] do

  end

end

app/models/client_browser.rb
class ClientBrowser < ActiveRecord::Base
end

app/models/client_os.rb
class ClientOS < ActiveRecord::Base
end

app/models/client_platform.rb
class ClientPlatform < ActiveRecord::Base
end

app/models/client_sample.rb
class ClientSample < ActiveRecord::Base
  before_save :sync_client_info
  belongs_to :browser, class_name: :ClientBrowser
  belongs_to :os, class_name: :ClientOS
  belongs_to :platform, class_name: :ClientPlatform

  PROTOCOLS = ['SSLv3', 'TLSv1', 'TLSv1.1', 'TLSv1.2']

private
  # Synchronises the useragent string with the individual columns.
  def sync_client_info
    if !useragent then
      return
    end

    ClientSample.transaction do |t|
      ua = UserAgent.parse(useragent)

      self.browser = ClientBrowser.find_or_create_by_browser(ua.browser)
      self.os = ClientOS.find_or_create_by_os(ua.os)
      self.platform = ClientPlatform.find_or_create_by_platform(ua.platform)
      self.version = ua.version.to_s
    end
  end
end

app/models/server_most_visit.rb
class ServerMostVisit < ActiveRecord::Base
  scope :with_untested, -> {
    joins('LEFT OUTER JOIN server_ssl_tests ON server_most_visits.id=server_ssl_tests.server_most_visit_id').
    where('server_ssl_tests.id IS NULL')
  }

  has_many :server_ssl_test
  alias :tests :server_ssl_test
end

app/models/server_ssl_test.rb
class ServerSslTest < ActiveRecord::Base
  # Selects the latest test for each server.
  scope :with_latest, -> { joins('INNER JOIN
    (SELECT server_most_visit_id, last_tested FROM server_ssl_tests GROUP BY server_most_visit_id) sst ON
    server_ssl_tests.server_most_visit_id=sst.server_most_visit_id AND
    server_ssl_tests.last_tested=sst.last_tested') }

  belongs_to :server_most_visit
  has_many :server_ssl_test_results
  alias :results :server_ssl_test_results
  alias :server :server_most_visit
end

app/models/server_ssl_test_result.rb
class ServerSslTestResult < ActiveRecord::Base
  belongs_to :server_ssl_test

  RATINGS = ['F', 'E', 'D', 'C', 'B', 'A-', 'A', 'A+'].freeze
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

private
  def trusted_proxy?(ip)
    ip =~ /^127\.0\.0\.1$|^(10|172\.(1[6-9]|2[0-9]|30|31)|192\.168)\.|^::1$|^fd[0-9a-f]{2}:.+|^localhost$/i
  end

protected
  # This will parse any proxy forwarding headers. This can be used as an action filter, like so:
  # before_action :patch_ip
  def patch_ip
    remote_addrs = request.headers['REMOTE_ADDR'] ? request.headers['REMOTE_ADDR'].split(/[,\s]+/) : []
    remote_addrs.reject! { |addr| trusted_proxy?(addr) }

    return if remote_addrs.any?

    forwarded_ips = request.headers['HTTP_X_FORWARDED_FOR'] ?
      request.headers['HTTP_X_FORWARDED_FOR'].strip.split(/[,\s]+/) : []
    logger.info('remote_addrs: ' + remote_addrs.to_s)

    if client_ip = request.headers['HTTP_CLIENT_IP']
      # If forwarded_ips doesn't include the client_ip, it might be an
      # ip spoofing attempt, so we ignore HTTP_CLIENT_IP
      if forwarded_ips.include?(client_ip) then
        request.headers['REMOTE_ADDR'] = client_ip
        return
      end
    end

    logger.info('forwarded_ips: ' + forwarded_ips.to_s)

    client_ip = forwarded_ips.reject { |ip| trusted_proxy?(ip) }.last
    request.headers['REMOTE_ADDR'] = client_ip if client_ip
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
    # Compute aggregate statistics
    @ssl_versions = map_versions_to_strings(ClientSample.group(:protocol).count)
    @ssl_versions_by_platform = ClientSample.group(:platform_id, :protocol).count
    @ssl_versions_by_platform = map_platforms_to_strings(@ssl_versions_by_platform)
    @ssl_versions_by_browser = ClientSample.group(:browser_id, :protocol).count
    @ssl_versions_by_browser = map_browsers_to_strings(@ssl_versions_by_browser)
  end

  def privacy

  end

private
  def map_versions_to_strings(versions)
    result = {}
    versions.each_pair do |key, value|
      result[ClientSample::PROTOCOLS[key]] = value
    end

    return result
  end

  def map_platforms_to_strings(platforms)
    result = {}
    all_platforms = {}
    ClientPlatform.all.each do |p|
      all_platforms[p.id] = p.platform
    end

    platforms.each_pair do |key, value|
      platform = all_platforms[key[0]]
      protocol = key[1]
      result[platform] = {} unless result[platform]
      result[platform][protocol] = value
    end

    result2 = {}
    result.each_pair do |platform, value|
      map_versions_to_strings(value).each_pair do |protocol, value|
        result2["#{platform}, #{protocol}"] = value
      end
    end

    return result2
  end

  def map_browsers_to_strings(browsers)
    result = {}
    all_browsers = {}
    ClientBrowser.all.each do |p|
      all_browsers[p.id] = p.browser
    end

    browsers.each_pair do |key, value|
      browser = all_browsers[key[0]]
      protocol = key[1]
      result[browser] = {} unless result[browser]
      result[browser][protocol] = value
    end

    result2 = {}
    result.each_pair do |browser, value|
      map_versions_to_strings(value).each_pair do |protocol, value|
        result2["#{browser}, #{protocol}"] = value
      end
    end

    return result2
  end
end

app/controllers/collector_controller.rb
class CollectorController < ApplicationController
  # Fix the remote IP address if we are on the collect action.
  before_action :patch_ip, only: :collect

  # The ports corresponding to the ClientSample PROTOCOLS constant.
  COLLECTOR_PORTS = [8009, 8010, 8011, 8012]

  # These browsers will be ignored.
  BLACKLISTED_BROWSERS = (Set.new ['facebookexternalhit']).freeze

  def index

  end

  def collect
    headers = request.headers
    if is_blacklisted?(headers['HTTP_USER_AGENT'])
      logger.info("Ignoring #{headers['HTTP_USER_AGENT']}")
      return send_image
    end

    protocol = params[:protocol]
    case protocol
      when 'ssl3'
        protocol = 0
        cookie_sym = :client_collected_ssl3
      when 'tls1'
        protocol = 1
        cookie_sym = :client_collected_tls1
      when 'tls11'
        protocol = 2
        cookie_sym = :client_collected_tls11
      when 'tls12'
        protocol = 3
        cookie_sym = :client_collected_ssl12
      else
        return send_image
    end

    if cookies[cookie_sym] then
      return send_image
    end
    cookies.permanent[cookie_sym] = true

    ClientSample.create({
                          protocol: protocol,
                          ip_address: headers['REMOTE_ADDR'],
                          useragent: headers['HTTP_USER_AGENT']
                        })

    send_image
  end

private
  def is_blacklisted?(useragent)
    ua = UserAgent.parse(useragent)
    return BLACKLISTED_BROWSERS.include?(ua.browser)
  end

  def send_image
    blank_image = File.open(File.join(Rails.root, 'app/assets/images/blank.png'), 'rb') do |f|
      f.read
    end
    
    send_data(blank_image, type: 'image/png',
              disposition: 'inline')
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index

  end

  def about

  end
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  def index
    @protocols = {
      'SSL v3' => 0,
      'TLS v1' => 0,
      'TLS v1.1' => 0,
      'TLS v1.2' => 0
    }
    ratings = [0, 0, 0, 0, 0, 0, 0, 0]

    ServerSslTestResult.all.joins(:server_ssl_test).merge(ServerSslTest.with_latest).each do |result|
      @protocols['SSL v3'] += result.ssl3 ? 1 : 0
      @protocols['TLS v1'] += result.tls1 ? 1 : 0
      @protocols['TLS v1.1'] += result.tls11 ? 1 : 0
      @protocols['TLS v1.2'] += result.tls12 ? 1 : 0
      if result.grade then
        ratings[result.grade] += 1
      end
    end

    @ratings = {};
    ratings.each_index {|index| @ratings[ServerSslTestResult::RATINGS[index]] = ratings[index]}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def controller?(*controller)
    controller.include?(params[:controller].to_sym)
  end

  def action?(*action)
    action.include?(params[:action].to_sym)
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/collector_helper.rb
module CollectorHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/clients/index.erb
<h1>User Statistics</h1>
<ul class="nav nav-tabs">
  <li class="active"><a href="#home" data-toggle="tab">Home</a></li>
  <li><a href="#protocol" data-toggle="tab">Broken down by protocol</a></li>
  <li><a href="#platform_then_protocol" data-toggle="tab">Broken down by platform</a></li>
  <li><a href="#browser_then_protocol" data-toggle="tab">Broken down by browser</a></li>
</ul>
<div class="tab-content">
  <div class="active fade in tab-pane" id="home"><div class="container row-fluid">
    Click on the tabs above to see the statistics, grouped in various ways.
  </div></div>
  <div class="tab-pane fade" id="protocol"><div class="container row-fluid">
    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8"><%= pie_chart @ssl_versions %></div>
  </div></div>
  <div class="tab-pane fade" id="platform_then_protocol"><div class="container row-fluid">
    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8"><%= pie_chart @ssl_versions_by_platform %></div>
  </div></div>
  <div class="tab-pane fade" id="browser_then_protocol"><div class="container row-fluid">
    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8"><%= pie_chart @ssl_versions_by_browser %></div>
  </div></div>
</div>

app/views/clients/privacy.erb
<h1>Privacy Policy</h1>
<ul>
  <li>I will only collection information about your computer that does not allow me to identify your identity.</li>
  <ul>
    <li>Information that allow tracking abuse will however be tracked. At this point in time, only your IP address is stored for this purpose.</li>
  </ul>
  <li>Also, at this point, insufficient information is collected to collectively identify users together. Only the information your browser reports is stored for purposes of research.</li>
  <ul>
    <li>Your browser's <em>user-agent</em> &dash; some information about your type and version of browser (e.g. Firefox 28), and some information about your operating system (e.g. Windows 8.1) is collected.</li>
  </ul>
</ul>

app/views/collector/index.erb
<h1>Participate</h1>
<div class="collection">
<% CollectorController::COLLECTOR_PORTS.each_index do |i| %>
  <img src="https://<%= request.host %>:<%= CollectorController::COLLECTOR_PORTS[i] %>"
       alt="Your browser could not understand <%= ClientSample::PROTOCOLS[i] %>" class="collection" />
<% end %>
</div>

<p>Thanks for participating! Your information will help us know more about the state of SSL/TLS Security in Singapore.</p>
<p><div class="btn-group"><%= link_to('View Statistics', clients_path, class: 'btn btn-primary') %></div></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SSL/TLS Standards</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="//code.highcharts.com/2.2/highcharts.src.js"></script>
  <%= javascript_include_tag 'chartkick',   'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body class="site">

<div class="container">
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to('Home', root_path, class: 'navbar-brand') %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav">
        <li <%= controller?(:main) && action?(:about) ? 'class="active"'.html_safe : '' %>><%= link_to('About', about_path) %></li>
        <li class="dropdown <%= controller?(:clients) || controller?(:collector) ? 'active' : '' %>">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Users <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to('Statistics', clients_path) %></li>
            <li><%= link_to('Participate', collect_clients_path) %></li>
          </ul>
        </li>

        <li ></li>
        <li <%= controller?(:servers) ? 'class="active"'.html_safe : '' %>><%= link_to('Servers', servers_path) %></li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>

<div class="<%= params[:controller] %>">
<%= yield %>
</div>
</div>

<footer><div class="container">
  <div class="pull-left">
    A project by <%= link_to('Joel Low', 'http://joelsplace.sg') %>
  </div>
  <ul class="links">
    <li><%= link_to('Privacy Policy', privacy_clients_path) %></li>
  </ul>
</div></footer>

</body>
</html>

app/views/main/index.erb
<div class="jumbotron">
  <h1>Singapore's SSL/TLS Standards</h1>
  <p>How securely configured are the information systems which we use every day?</p>
  <p>
    <%= link_to('Learn More', about_path, class: 'btn btn-primary btn-lg') %>
    <%= link_to('Participate in the Survey', collect_clients_path, class: 'btn btn-primary btn-lg') %>
  </p>
</div>
<hr />

app/views/servers/index.erb
<h1>Server Statistics</h1>
<ul class="nav nav-tabs">
  <li class="active"><a href="#home" data-toggle="tab">Home</a></li>
  <li><a href="#protocol" data-toggle="tab">Broken down by protocol</a></li>
  <li><a href="#rating" data-toggle="tab">Broken down by rating</a></li>
</ul>
<div class="tab-content">
  <div class="active fade in tab-pane" id="home"><div class="container row-fluid">
    <p>Click on the tabs above to see the statistics, grouped in various ways.</p>
    <p>The servers sampled have been mainly gathered from the Alexa Top 500 sites for Singapore. There have been a few manual additions which might require SSL/TLS to be used (e.g. internet banking, shopping, government sites etc.) The owners of these sites have not yet been informed of my findings, hence in the interest of responsible disclosure, I will currently only publish aggregated information.</p>
    <p>There are more samples than there are sites because each website might have multiple servers configured (e.g. for load balancing.) Each physical server constitutes one sample. Some sites also do not have SSL/TLS enabled.</p>
  </div></div>
  <div class="tab-pane fade" id="protocol"><div class="container row-fluid">
    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8"><%= pie_chart @protocols %></div>
  </div></div>
  <div class="tab-pane fade" id="rating"><div class="container row-fluid">
    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8"><%= pie_chart @ratings %></div>
    <p>The rating guide for web sites can be found on <a href="https://www.ssllabs.com/projects/rating-guide/index.html">Qualys' web site</a>.</p>
  </div></div>
</div>